"""empty message

Revision ID: 034f51af9429
Revises: f3332786bb2e
Create Date: 2023-08-17 12:05:30.384113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '034f51af9429'
down_revision = 'f3332786bb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('application_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fund_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_feedback_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('id', 'section_id', name=op.f('uq_feedback_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
