"""empty message

Revision ID: 7f59d060561a
Revises: 755b1be91ed5
Create Date: 2022-09-22 09:41:50.847076

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7f59d060561a"
down_revision = "755b1be91ed5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_completed", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.drop_column("has_completed")

    # ### end Alembic commands ###
