"""empty message

Revision ID: a0b9e8f859a9
Revises: 5bf853808dfb
Create Date: 2022-11-01 16:53:20.200347

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a0b9e8f859a9"
down_revision = "5bf853808dfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
