"""empty message

Revision ID: b2f22185655c
Revises: 755b1be91ed5
Create Date: 2022-09-16 18:35:47.922378

"""
import uuid

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b2f22185655c"
down_revision = "7f59d060561a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "key",
                sa.String(),
                nullable=False,
                server_default=str(uuid.uuid4()),
            )
        )
        batch_op.alter_column("key", server_default=None)
        batch_op.add_column(
            sa.Column(
                "reference",
                sa.String(),
                nullable=False,
                server_default=str(uuid.uuid4()),
            )
        )
        batch_op.alter_column("reference", server_default=None)
        batch_op.create_unique_constraint(
            "_reference", ["fund_id", "round_id", "key"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_applications_reference"), ["reference"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_applications_reference"), type_="unique"
        )
        batch_op.drop_constraint("_reference", type_="unique")
        batch_op.drop_column("reference")
        batch_op.drop_column("key")

    # ### end Alembic commands ###
