"""empty message

Revision ID: c762d7b25809
Revises: 755b1be91ed5
Create Date: 2022-09-16 18:19:41.867476

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c762d7b25809"
down_revision = "755b1be91ed5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("key", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("reference", sa.String(), nullable=False)
        )
        batch_op.create_unique_constraint(
            "_reference", ["fund_id", "round_id", "key"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_constraint("_reference", type_="unique")
        batch_op.drop_column("reference")
        batch_op.drop_column("key")

    # ### end Alembic commands ###
