"""empty message

Revision ID: eb61bc354c57
Revises: d37dca03b539
Create Date: 2024-05-30 14:49:25.748523

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "eb61bc354c57"
down_revision = "d37dca03b539"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_survey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.String(), nullable=False),
        sa.Column("round_id", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("date_submitted", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_research_survey_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_survey")),
        sa.UniqueConstraint("application_id", name=op.f("uq_research_survey_application_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("research_survey")
    # ### end Alembic commands ###
