"""empty message

Revision ID: f3332786bb2e
Revises: 5bf853808dfb
Create Date: 2022-11-10 11:47:03.141413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3332786bb2e'
down_revision = '5bf853808dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    language_enum = postgresql.ENUM('en', 'cy', name='language')
    language_enum.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', language_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
