"""empty message

Revision ID: fb1fc6f98311
Revises: 755b1be91ed5
Create Date: 2022-09-16 12:05:13.923566

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "fb1fc6f98311"
down_revision = "755b1be91ed5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("app_id", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("readable_id", sa.String(), nullable=False)
        )
        batch_op.create_unique_constraint(
            "_short_app_id", ["fund_id", "round_id", "app_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_constraint("_short_app_id", type_="unique")
        batch_op.drop_column("readable_id")
        batch_op.drop_column("app_id")

    # ### end Alembic commands ###
