Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

Resources:
  FormUploadsBucket:
    Metadata:
      'aws:copilot:description': 'An Amazon S3 bucket, form-uploads, for storing and retrieving objects'
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  FormUploadsBucketPolicy:
    Metadata:
      'aws:copilot:description': 'A bucket policy to deny unencrypted access to the bucket and its contents'
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ForceHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub ${ FormUploadsBucket.Arn}/*
              - !Sub ${ FormUploadsBucket.Arn}
            Condition:
              Bool:
                "aws:SecureTransport": false
      Bucket: !Ref FormUploadsBucket

Outputs:
  FormUploadsName:
    Description: "The name of a user-defined bucket."
    Value: !Ref FormUploadsBucket
    Export:
      Name: !Sub fsd-form-uploads-${Env}
  FormUploadsBucketARN:
    Description: "The ARN of the form-uploads bucket."
    Value: !GetAtt FormUploadsBucket.Arn
    Export:
      Name: !Sub ${App}-${Env}-FormUploadsBucketARN
