name: Deploy to Gov PaaS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'

jobs:

  testing-unit: 
    runs-on: ubuntu-latest
    environment: Dev
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      - name: install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements-dev.txt
      - name: run migrations
        run: flask db migrate
      - name: run unit tests
        # pytest -m "not accessibility" runs every test which is not marked 
        # accessibility.
        run: python -m pip install pytest && python -m pytest -k test_create_application

  test_and_deploy:
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/deploy.yml@main
    with:
      app_name: ${{ github.event.repository.name }}
      api: true
      users: 2
      spawn-rate: 2
      run-time: 11s
    secrets:
      CF_API: ${{secrets.CF_API}}
      CF_ORG: ${{secrets.CF_ORG}}
      CF_SPACE: ${{secrets.CF_SPACE}}
      CF_USER: ${{secrets.CF_USER}}
      CF_PASSWORD: ${{secrets.CF_PASSWORD}}
