name: Use Paketo to package and build python application

permissions:
  packages: write

on:
  workflow_call:
    inputs:
      version_to_build:
        type: string
        required: true

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: funding-service-design-application-store

jobs:
  paketo_build:
    runs-on: ubuntu-latest
    name: Packaging and building the application
    steps:
      - uses: buildpacks/github-actions/setup-pack@v5.0.0
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish app image
        run: "pack build ${{ env.DOCKER_IMAGE }} --builder paketobuildpacks/builder:base"

      - name: Push image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=${{ inputs.version_to_build }}

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag ${{ env.DOCKER_IMAGE }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
